version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tdmk-sql-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: always
    networks:
      - tdmk-network

  backend:
    image: ${DOCKERHUB_USERNAME}/tdmk-backend:latest
    container_name: tdmk-running-app
    depends_on:
      - db
    ports:
      - "7287:8081"
    environment:
      - ASPNETCORE_HTTP_PORTS=8081
      - ASPNETCORE_URLS=http://+:8081
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=${DB_NAME};User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True
      - FileStorage__UploadFolder=/app/wwwroot/uploads
    volumes:
      - tdmk_uploads:/app/wwwroot/uploads
    restart: always
    networks:
      - tdmk-network

  frontend:
    image: ${DOCKERHUB_USERNAME}/tdmk-frontend:latest
    container_name: tdmk-frontend-app
    ports:
      - "7288:3000"
    environment:
      - NUXT_PUBLIC_API_BASE=https://api.tdmk.vn
      - NUXT_PUBLIC_HUB_URL=https://api.tdmk.vn/hubs/monitor
    restart: always
    networks:
      - tdmk-network

networks:
  tdmk-network:
    driver: bridge

volumes:
  mssql_data:
  tdmk_uploads: